### ISSUE TITLE
Glass bottle Mold knapping recipe duplicates Glass Pane Mold knapping recipe

### ISSUE THREAD

**Issue by kati0na** [TheNimbleNinja/Terrafirmacraft-omega#2]
![image](https://user-images.githubusercontent.com/98770669/199454022-72e59538-91a6-4e3a-a1f8-ae6b71451f66.png)
![image](https://user-images.githubusercontent.com/98770669/199454150-3bfbf8e8-aefc-4264-9bbc-ee6aa794163e.png)
making it impossible to craft the latter, which i didn't really need yet, but still

I have a suggestion for an easy fix: to alter the bottle recipe in \scripts\contenttweaker\recipes\TFC part making.zs, line 209 
from

> ClayKnapping.addRecipe("glass_bottle_mold", <contenttweaker:unfired_glass_bottle_mold>, "XXXXX", "X   X", "X   X", "X   X", "XXXXX");

to

> ClayKnapping.addRecipe("glass_bottle_mold", <contenttweaker:unfired_glass_bottle_mold>, "X   X", "XX XX", "X   X", "X   X", "XXXXX");

or another unique pattern
(sorry idk how to prevent multiple whitespace removal, but you get the idea)
(also i did notice that this file does not come with the modpack, but is generated automatically... - well, it did automatically generate a recipe collision, so i suggest to state a unique recipe preemptively)

**Comment by TheNimbleNinja** [comment]
fixed in dev!
