### ISSUE TITLE
Grain stacking - probably a TFC bug and not the modpack one

### ISSUE THREAD

**Issue by kati0na** [TheNimbleNinja/Terrafirmacraft-omega#3]
![image](https://user-images.githubusercontent.com/98770669/199458183-7eb91ab2-42b5-4bde-a1c2-b18c6dd9cc0e.png)
Shift+left click...
![image](https://user-images.githubusercontent.com/98770669/199458546-86a88834-e44f-433a-9020-58e2c738925e.png)
And these have drastically different decay
![image](https://user-images.githubusercontent.com/98770669/199458789-6a4c7c7e-89d0-4e8b-9c7f-7aff5c3c78d4.png)
![image](https://user-images.githubusercontent.com/98770669/199458978-8465315b-ba93-4071-b9f0-d8f042b28c2a.png)
All five of these were the same, i mean, shouldn't they stay the same

**Comment by TheNimbleNinja** [comment]
i think they have differnt decay times so they cant stack sadly

**Comment by kati0na** [comment]
Haha yes they do, but why do they if they were the same stack, had the same decay time AND were converted at the same moment with the same click?
