### ISSUE TITLE
Pit Kiln quest description - guide info is not true

### ISSUE THREAD

**Issue by kati0na** [TheNimbleNinja/Terrafirmacraft-omega#4]
![image](https://user-images.githubusercontent.com/98770669/199462402-d92e088a-3850-4db3-95a6-183c3bc82828.png)
This info is false, shift+right clicking doesn't work, 'v' button should be pressed in order to place any item anywhere

**Comment by TheNimbleNinja** [comment]
oof XD

**Comment by kati0na** [comment]
yeah, imagine my face when i shift+rightclick as it was in 1.7 aaaand... nothing happens lol

**Comment by TheNimbleNinja** [comment]
fixed in dev
