### ISSUE TITLE
Quern quest reward is rotten

### ISSUE THREAD

**Issue by kati0na** [TheNimbleNinja/Terrafirmacraft-omega#6]
![image](https://user-images.githubusercontent.com/98770669/199484424-0b18bd87-b771-4b00-bef9-ef75c2e6f127.png)
I do not know what exactly caused this, but here it is
Maybe i really took my time with the quern, i am not sure

**Comment by TheNimbleNinja** [comment]
sadly food items cant be used in quests as you can see they become rotten

**Comment by TheNimbleNinja** [comment]
i need to change that quest reward

**Comment by kati0na** [comment]
i guess so
-- or there might be a workaround like some non-decaying item that transforms into food (uncraftable, specifically for quest rewards)
... but it's a lot of work and probably not really important

**Comment by kati0na** [comment]
i have another idea
can the reward be a command '/give'? it might not be spoiled that way

**Comment by TheNimbleNinja** [comment]
hmm that might work

**Comment by TheNimbleNinja** [comment]
fixed in dev :)
