### ISSUE TITLE
Fishy Fishing woahs

### ISSUE THREAD

**Issue by kati0na** [TheNimbleNinja/Terrafirmacraft-omega#7]
![image](https://user-images.githubusercontent.com/98770669/199486477-75278b16-97cd-479d-b856-2322a363d687.png)
Starting quest for this questline suggests the player to get a Minecraft fishing rod
![image](https://user-images.githubusercontent.com/98770669/199486955-eaa6f169-1eea-44a8-9a10-36528d7045b7.png)
However, catching anything listed below it requires an Aquaculture fishing rod

These two items, despite looking the same, seem to have different loot tables - vanilla drops on a vanilla rod, Aquaculture drops on Aquaculture rod.

**Comment by TheNimbleNinja** [comment]
fixed in dev
