### ISSUE TITLE
Suggestion - Breadmaking questline

### ISSUE THREAD

**Issue by kati0na** [TheNimbleNinja/Terrafirmacraft-omega#8]
After a quern, there could be 
- a quest with a gude on how to make a FirmaLife oven
- quests for making or getting ingredients for bread like making flour from any grain and finding salt, 
- also maybe yeast and sugar for the second tier

Not sure how it should be arranged since it requires some achievements from some other questlines
Maybe it can be a part of a "cooking woahs" section since there are other food options in the modpack

**Comment by TheNimbleNinja** [comment]
anything sadly to do with food cant be used in a quest as they become rotten i might be able to have quests that request said item but cant reward said item

**Comment by TheNimbleNinja** [comment]
i might of dmed you on discord as i think you joined my discord

**Comment by TheNimbleNinja** [comment]
i dont think i can currently make a food creation questline without making custom items for each food and that doesnt sound good in my opinion but i can make a quest for the oven!
